### ISSUE TITLE
I can not load GlobalVariable.Hostname

### ISSUE THREAD

**Issue by kazurayam** [kazurayam/ExecutionProfilesLoader#2]
I had a Profile "Cure_DevelopmentEnv" with a property named `Hostname`
<img width="832" alt="スクリーンショット 2021-07-10 11 09 06" src="https://user-images.githubusercontent.com/4467417/125148772-96a5cd80-e16f-11eb-91ce-9a0295385837.png">

I wrote a test case
```
import com.kazurayam.ks.globalvariable.ExecutionProfilesLoader

new ExecutionProfilesLoader().loadProfile("CURA_DevelopmentEnv")
```

It failed

```
2021-07-10 11:13:15.078 ERROR c.k.katalon.core.main.TestCaseExecutor   - ❌ Test Cases/CURA/Execute_twins FAILED.
Reason:
java.lang.IllegalArgumentException: name=Hostname must not start with a uppercase letter followed by a lower case letter
	at com.kazurayam.ks.globalvariable.ExpandoGlobalVariable.validateVariableName(ExpandoGlobalVariable.groovy:122)
	at com.kazurayam.ks.globalvariable.ExpandoGlobalVariable.addGlobalVariable(ExpandoGlobalVariable.groovy:51)
	at com.kazurayam.ks.globalvariable.ExpandoGlobalVariable$addGlobalVariable$0.call(Unknown Source)
	at com.kazurayam.ks.globalvariable.ExecutionProfilesLoader$_loadProfiles_closure2$_closure5.doCall(ExecutionProfilesLoader.groovy:75)
	at com.kazurayam.ks.globalvariable.ExecutionProfilesLoader$_loadProfiles_closure2.doCall(ExecutionProfilesLoader.groovy:72)
	at com.kazurayam.ks.globalvariable.ExecutionProfilesLoader.loadProfiles(ExecutionProfilesLoader.groovy:70)
	at com.kazurayam.ks.globalvariable.ExecutionProfilesLoader$loadProfiles$0.callCurrent(Unknown Source)
	at com.kazurayam.ks.globalvariable.ExecutionProfilesLoader.loadProfile(ExecutionProfilesLoader.groovy:46)
	at com.kazurayam.ks.globalvariable.ExecutionProfilesLoader$loadProfile.call(Unknown Source)
	at Execute_twins.run(Execute_twins:6)
	at com.kms.katalon.core.main.ScriptEngine.run(ScriptEngine.java:194)
	at com.kms.katalon.core.main.ScriptEngine.runScriptAsRawText(ScriptEngine.java:119)
	at com.kms.katalon.core.main.TestCaseExecutor.runScript(TestCaseExecutor.java:398)
	at com.kms.katalon.core.main.TestCaseExecutor.doExecute(TestCaseExecutor.java:389)
	at com.kms.katalon.core.main.TestCaseExecutor.processExecutionPhase(TestCaseExecutor.java:368)
	at com.kms.katalon.core.main.TestCaseExecutor.accessMainPhase(TestCaseExecutor.java:360)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:255)
	at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:114)
	at com.kms.katalon.core.main.TestCaseMain.runTestCase(TestCaseMain.java:105)
	at com.kms.katalon.core.main.TestCaseMain$runTestCase$0.call(Unknown Source)
	at TempTestCase1625883187369.run(TempTestCase1625883187369.groovy:25)

```

It will accept `hostname` and `HOSTNAME` but it does not accept `Hostname`.

This behaviour of `loadProfile()` is very incovenient.
 
It should accept "Hostname" as well.

**Comment by kazurayam** [comment]
v1.2.0 fixed this.

A property "Hostname" declared in a Execution Profile will be silently accepted.

But still you can not add a new property "Abc" with ExpandGlobalVariable.addProperty("Abc", "value"). This restriction would not matter too much.

**Comment by kazurayam** [comment]
>But still you can not add a new property "Abc" with ExpandGlobalVariable.addProperty("Abc", "value").

This restriction is not acceptable.

Reopened this issue.

**Comment by kazurayam** [comment]
I should step back and think, why a new property in ExpandoGlobalVariable should not benamed with a string starting with a uppercase letter followed by a lower case letter?

**Comment by kazurayam** [comment]
Let me think of 2 cases:

1. I want to add a GlobalVariable named "username"
2. I want to add a GlobalVaraible named "Username"

In the v 1.2.0, ExpandoGlobalVariable class https://github.com/kazurayam/ExecutionProfilesLoader/tree/e0ef571912687a6f97cfb63b3c63f3069c1169c0 has following code snippet:

```
	private static String getGetterName(String name) {
		return 'get' + getAccessorName(name)
	}

	private static String getSetterName(String name) {
		return 'set' + getAccessorName(name)
	}


	private static String getAccessorName(String name) {
		return ((CharSequence)name).capitalize()
	}
```

As the code is as such,

**Comment by kazurayam** [comment]
As long as I do NOT try to add both of `Username` and `username`, perhaps no problem occurs.

**Comment by kazurayam** [comment]
I have got an idea of betterment.

(1) validatePropertyName(String name) should not check out UPPER_LOWER pattern as error


	static void validatePropertyName(String name) {
		Objects.requireNonNull(name)
		if (PTTN_LEADING_DIGITS.matcher(name).find()) {
			throw new IllegalArgumentException("name=${name} must not start with digits")
		}
		if (PTTN_LEADING_PUNCTUATIONS.matcher(name).find()) {
			throw new IllegalArgumentException("name=${name} must not start with punctuations")
		}
		<s>if (PTTN_UPPER_LOWER.matcher(name).find()) {
			throw new IllegalArgumentException("name=${name} must not start with a uppercase letter followed by a lower case letter")
		}</s>
	}

**Comment by kazurayam** [comment]
In the ExpandoGlobalVariableTest class I wrote:
```
@Test
	void test_addProperty_Username() {
		EGV.clear()
		//
		EGV.addProperty("password", "password")
		assertEquals("password", GlobalVariable.getPassword())		// this statement passes
		assertEquals("password", GlobalVariable.password)			// this statement passes as well
		//
		EGV.addProperty("Username", "Username") 
		assertEquals("Username", GlobalVariable.getUsername())		// this statement passes
		assertEquals("Username", GlobalVariable.Username)			// this statement throws an Exception
		/*
		 * groovy.lang.MissingPropertyException: No such property: Username for class: internal.GlobalVariable
		 *   at com.kazurayam.ks.globalvariable.ExpandoGlobalVariableTest.test_addProperty_Username(ExpandoGlobalVariableTest.groovy:177)
		 *   at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
		 */
	}
```

The result of this test tells me somthing interesting.

**Comment by kazurayam** [comment]
Perhaps I need to read "propertyMissing" section in the official document

https://groovy-lang.org/metaprogramming.html#_propertymissing

**Comment by kazurayam** [comment]
Java Bean naming rule tells that a property should not be named with Upper case letter followed by Lower case letter.

https://irof.hateblo.jp/entry/20090623/p1

**Comment by kazurayam** [comment]
I need to read the Groovy's fundamentals.

https://groovy-lang.org/objectorientation.html#_fields_and_properties

**Comment by kazurayam** [comment]
In the Libs/internal/GlobalVariable.groovy source code, I could find

```
class GlobalVariable {
    public static Object Username;
}
```

In this case, `Username` is just a public field. Applications can read/write `Username` by the following notation:

```
GlobalVariable.Username = 'foo'
assert GlobalVariable.Username == 'foo'
````

**Comment by kazurayam** [comment]
On the otherhand, 
```
ExpandoGlobalVariable.addProperty('username', 'foo)
```
This looks that I added a Property into ExpandoGlobalVariable.

In fact, it is not very correct.

I added `static Object getUsername()` method and `static void setUsername(Objejct)` method. So
```
EGV.username = 'foo'
assert EGV.username == 'foo'
```

Groovy silently interprete this according to the "JavaBean naming rule" into the following:

```
EGV.setUsername("foo")
assert EGV.getUsername()
```

and this works.

However, `Username` which starts with a Uppercase letter followed by Lower case letter stands against the "JavaBean naming rule". The following would not work.

```
EGV.addProperty("Username", "foo")
assert EGV.Username == "foo"
```

This will throw MissingPropertyException.

**Comment by kazurayam** [comment]
So it is difficult to fix this issue completely.

**Comment by kazurayam** [comment]
I have a doubt.

In one of my Katalon Studio project (VisualTestingInKatalonStudio_revive), a GlobalVariable named `Username` is defined in  an Execution Profile. A name defined in any Execution Profile should be regarded a `public static` field in GlobalVariable class. It should never cause MissingPropertyException. But in fact in the project, I sometimes see the Exception. I wonder why. There seems to be another aspect I should look into.
